### PR TITLE
Add flag for generating ygot setters.

### PR DESCRIPTION
**Pull request by wenovus**
Use case is `intf.SetDescription(s)` instead of `intf.Description = ygot.String(s)`, it also permits writing interfaces based on these setters' signatures.

I made this a flag since there could be conflicts. Also made this true by default. This might break some users but if we don't make it default now it will be harder to justify later on as more people depend on ygnmi.

Alternatively we can make it always `true` but since this is a new flag in ygot some folks might already be depending on it not being there, so breaking them just because of this doesn't seem like a good idea.

### CODE REVIEW

**Comment by DanG100** [comment]
I think I'd rather this be always be true. This just add a method so it isn't a backwards incompatible change. I'd like to see more concrete use cases first as this rather expensive in terms generated code.

**Comment by wenovus** [comment]
> I think I'd rather this be always be true. This just add a method so it isn't a backwards incompatible change. I'd like to see more concrete use cases first as this rather expensive in terms generated code.

So this could be a backwards-incompatible change if there is any leaf named "set-leaf" in addition to "leaf". Although this is unlikely and ygnmi is still relatively new, any usage with previous ygot-compatible YANG files might hit an issue. I guess I would be OK with this being true all the time. Do you see a clear downside to providing an option for users?

@dan-lepage do you have any thoughts on how useful this flag will be in Ondatra tests?

**Comment by dan-lepage** [comment]
> @dan-lepage do you have any thoughts on how useful this flag will be in Ondatra tests?

Yes, I think we'd use this a lot. It's certainly a little cleaner and more readable to use `intf.SetDescription("foo")` instead of `intf.Description = ygot.string("foo")` and it means we can write `timer.SetRestartTime(10)` instead of having to remember whether it takes a uint8 or a uint16, but most importantly it would let us write helpers that don't depend on a specific generated ygot library.

For example in [attrs.go](https://github.com/openconfig/featureprofiles/blob/000c474994c66c24576c3880dde792414ddccd49/internal/attrs/attrs.go#L59) we have a function that takes a `*github.com/openconfig/ondatra/telemetry.Interface` and modifies it, and in some code I'm working on to port tests to ygnmi I had to duplicate that function entirely just to do the same thing for a `*github.com/openconfig/ondatra/gnmi/oc.Interface` (the functions are literally identical except for the package name before the word `Interface`). This would be much simpler if we could define an interface with the parts we care about and then use the helper with any ygot-generated library that provides those helpers.

**Comment by wenovus** [comment]
On the question of expensiveness, this change is as expensive as the ygot getters. Here is a comparison between generating vs. not generating based on ygot's exampleoc (which contains network-instance):

No Setter: 244730 LoC
```
        Command being timed: "go build -a"
        User time (seconds): 114.74                
        System time (seconds): 10.41         
        Percent of CPU this job got: 348%   
        Elapsed (wall clock) time (h:mm:ss or m:ss): 0:35.95
        Average shared text size (kbytes): 0
        Average unshared data size (kbytes): 0
        Average stack size (kbytes): 0
        Average total size (kbytes): 0
        Maximum resident set size (kbytes): 3574892
        Average resident set size (kbytes): 0
```

Setter: 269188 LoC
```
        Command being timed: "go build -a"
        User time (seconds): 118.51
        System time (seconds): 10.11
        Percent of CPU this job got: 359%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 0:35.78
        Average shared text size (kbytes): 0
        Average unshared data size (kbytes): 0
        Average stack size (kbytes): 0
        Average total size (kbytes): 0
        Maximum resident set size (kbytes): 3655512
        Average resident set size (kbytes): 0
```

So both time and memory-wise the increase is less than 5%. There is indeed more LoC in the generated file but I think this is less of a problem.

**Comment by dan-lepage** [comment]
Another possible advantage to building helpers that don't rely on a specific yang-generated tree is that I think it might be possible to vastly speed up compile times for small projects by compiling an OC tree with just the subset of OC that you actually use.

**Comment by DanG100** [comment]
sgtm, i think this should be always true in that case.

**Review by DanG100 — APPROVED** [review]

**Pull request merged**
